### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by Miserlou** [Kickflip/kickflip-android-sdk#14]
This snippet is suggested by the README of this repo:

    @Override
    public void onBroadcastLive(String watchUrl) { 
        Log.i("Kickflip", "This phone is live at " + watchUrl);       
    }

But I think that String is now a Stream object, so the @Override won't work and the project and the code won't compile. Simple fix, just gotta make sure the docs match the interface.

**Comment by OnlyInAmerica** [comment]
fixed in 0ff7f5a
