### ISSUE TITLE
Kickflip for x86

### ISSUE THREAD

**Issue by Miserlou** [Kickflip/kickflip-android-sdk#15]
What would it take to get this supported added in to Kickflip?

I use the x86 VM to develop (so much faster than the emulator.. soooo much faster..), but unfortunately the project won't compile without x86 support:

Failure [INSTALL_FAILED_CPU_ABI_INCOMPATIBLE]

How much would it inflate the package to add this?

**Comment by kenyee** [comment]
Ditto...Please add x86 JNI libraries for ffmpeg.  Or point to the project used to build the ARM JNI libraries so we can rebuild it...

**Comment by OnlyInAmerica** [comment]
Preliminary x86 support added in [6b4b3a](https://github.com/Kickflip/kickflip-android-sdk/commit/6b4b3abbf29a8aaa021cc03be79a1e9cecc815a8). I don't have any x86 devices with cameras so if somebody could provide feedback that would be great.

Please also note the `preview` branch is not yet stable so please 'ignore' any crashes that happen after the camera preview becomes active. If you get to the point where you're viewing the Kickflip broadcast UI the x86 libraries will have been successfully loaded.
