### ISSUE TITLE
Trable with my account and plan

### ISSUE THREAD

**Issue by Darwinium** [Kickflip/kickflip-android-sdk#21]
Excuse me, that I write here, but is not responding technical support for a month. How do I delete my account or a credit card because I have already 2 months did not use the service, but my money is debited monthly.

thanks a lot

**Comment by OnlyInAmerica** [comment]
I'm sorry for the trouble and I've cancelled your subscription.

**Comment by Darwinium** [comment]
Thanks, but my subscription does not cancelled (
Account login: id@igsystems.ru

I am sorry that I wrote about it here

**Comment by OnlyInAmerica** [comment]
I have not deleted your Kickflip account credentials, but rather cancelled your current subscription. This means you can still log in to Kickflip and manage your existing recordings but you will no longer be charged any monthly payments.
