### ISSUE TITLE
Problem with jni modules

### ISSUE THREAD

**Issue by niveuseverto** [Kickflip/kickflip-android-sdk#22]
Modules introduced in 6b4b3abbf29a8aaa021cc03be79a1e9cecc815a8 have problem:
`java.lang.UnsatisfiedLinkError: dlopen failed: could not load library "libavformat-56.so" needed by "libFFmpegWrapper.so"; caused by could not load library "libavcodec-56.so" needed by "libavformat-56.so"; caused by could not load library "libswresample-1.so" needed by "libavcodec-56.so"; caused by could not load library "libavutil-54.so" needed by "libswresample-1.so"; caused by could not load library "librtmp-1.so" needed by "libavutil-54.so"; caused by cannot locate symbol "rand" referenced by "librtmp-1.so"...`
Tested on Xiaomi Mi3 (Android 4.4.4).

At stackoverflow were hints, that this can be becourse this modules were compiled with NDK API 21. 

Could you please provide C code for net.openwatch.ffmpegwrapper.FFmpegWrapper as OpenWatch/FFmpegWrapper-Android is outdated?

**Comment by OnlyInAmerica** [comment]
This issue should now be addressed in the kickflip-android-sdk master branch.

I've also just updated OpenWatch/FFmpegWrapper-Android. That repository now reflects the exact configuration used to build libFFMpegWrapper.so for Kickflip.
