### ISSUE TITLE
FFmpeg crashing with exception on Kitkat device

### ISSUE THREAD

**Issue by ckarthikv** [Kickflip/kickflip-android-sdk#25]
Build fingerprint: 'Xiaomi/cancro/cancro:4.4.2/KVT49L/KXDMIBF23.0:user/release-keys'
Revision: '0'
pid: 25070, tid: 25963, name: Thread-1763  >>> ... <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000005
    r0 00000000  r1 00000000  r2 0000000d  r3 00000005
    r4 8e25e9fe  r5 00000000  r6 78409a48  r7 00000000
    r8 0000000d  r9 78409a48  sl 7863e9a0  fp 000001c8
    ip 76f96e68  sp 78409a00  lr 76eef6cc  pc 7c385714  cpsr 200d0010
    d0  6f7262642f6f7270  d1  776765706d66662f
    d2  462f726570706172  d3  6172576765706d46
    d4  0000000100000000  d5  0000000000000000
    d6  0000000000000000  d7  0000000000000000
    d8  0000000000000000  d9  461c40003f000000
    d10 00000000445fdb65  d11 0000000000000000
    d12 0000000000000000  d13 0000000000000000
    d14 0000000000000000  d15 0000000000000000
    d16 ffffffffffffffff  d17 0000000000000000
    d18 0000000000000000  d19 0000000d00000000
    d20 0000000000000001  d21 0000000000000000
    d22 0000000000000000  d23 00720077002f0072
    d24 3fc748e72055a505  d25 3fc2f112df3e5244
    d26 c047069e2aa2aa5b  d27 0000000000000000
    d28 001e001d001c001b  d29 0020001f001d001e
    d30 002a002a002a002a  d31 0000000000000000
    scr 88000013

backtrace:
    #00  pc 000e2714  /data/app-lib/.../libavcodec-55.so (av_packet_split_side_data+52)
    #01  pc 000996c8  /data/app-lib/.../libavformat-55.so (av_write_trailer+216)

code around pc:
    7c3856f4 1a000022 e596801c e358000c da00001d  
    7c385704 e5967018 e59f4290 e0872008 e2423008  
    7c385714 e5529008 e552b007 e5d3a005 e5522004  
    7c385724 e5d3c002 e5d31006 e182a40a e189940b  
    7c385734 e5d32003 e5d33007 e189980c e18aa801  
    7c385744 e1899c02 e18aac03 e02ac86a e0291869  
    7c385754 e1a0c42c e1a01421 e59f5240 e3ccccff  
    7c385764 e3c11cff e02c246a e0213469 e1530005  
    7c385774 01520004 0a000004 e28dd00c e8bd8ff0  
    7c385784 e3a00000 e28dd00c e8bd8ff0 e248800d  
    7c385794 e0873008 e5d31001 e7d72008 e5d3c002  
    7c3857a4 e1822401 e5d31003 e182280c e1822c01  
    7c3857b4 e0221862 e1a01421 e3c11cff e0312462  
    7c3857c4 4affffec e0671003 e1520001 8affffe9  
    7c3857d4 e3a0c001 ea000011 e3e01004 e0621001  
    7c3857e4 e7f32001 e28cc001 e5d31001 e5d34002 

code around lr:
    76eef6ac e3510102 03500000 0a000002 e0922000  
    76eef6bc e0a33001 e1cd22f0 e1a00009 ebfdd841  
    76eef6cc e5983008 e1a01009 e5933034 e1a05000  
    76eef6dc e1a00008 e12fff33 e59834c0 e3530000  
    76eef6ec e1a04000 0a000007 e5980010 e3500000  
    76eef6fc 0a000004 e3540000 ba000002 e598343c  
    76eef70c e3130c02 1a000065 e3550000 0a000001  
    76eef71c e1a00009 ebfdd82e e3540000 ba000051  
    76eef72c e598301c e59d2038 e1a00009 e7931102  
    76eef73c e1c124d0 e2922001 e2a33000 e1c124f0  
    76eef74c ebfdd59b e5980010 e3500000 0affffac  
    76eef75c e590304c e3530000 0affffa9 e3500000  
    76eef76c 0a000000 ebfe4808 e3540000 1a000002  
    76eef77c e5983010 e3530000 1593404c e5983018  
    76eef78c e3530000 13a06000 11a05006 0a00000c  
    76eef79c e598301c e2855001 e7930106 e280

**Comment by OnlyInAmerica** [comment]
just released a new version (1.3) with an updated FFmpeg build which should be available on Maven Central in ~2hrs. Please give it a try by adding kickflip-android-sdk as a submodule or waiting for the Maven artifact to become available.

**Comment by ckarthikv** [comment]
Sure, will check. Any reason why RTMP support has been removed?

**Comment by OnlyInAmerica** [comment]
RTMP adds significant weight to the project (it requires openssl and librtmp) and I'm not happy with the proprietary backend infrastructure required to operate with it. I'm personally interested in eventually solving the realtime problem with WebRTC - something I hope to have experimental support for this summer.

**Comment by OnlyInAmerica** [comment]
Closing this now. Feel free to re-open if you have additional issues.
