### ISSUE TITLE
How to reduce number of items in index.m3u8

### ISSUE THREAD

**Issue by gouravd** [Kickflip/kickflip-android-sdk#28]
I am not able to figure out how to reduce the number of items in index.m3u8 to 3. Currently 5 items are listed and it adds to the lag,

I cannot find the code which creates, updates the index.m3u8. Also, is there a way for the player to start playing from the last .ts file in the m3u8?

**Comment by OnlyInAmerica** [comment]
When FFmpeg updates the index.m3u8 Kickflip catches the filesystem write and processes the updated manifest in [`Broadcaster#onManifestUpdated(...)`](https://github.com/Kickflip/kickflip-android-sdk/blob/c10ef0961141aba46594b781814eff6c23de453c/sdk/src/main/java/io/kickflip/sdk/av/Broadcaster.java#L338). Note the last two lines (three if it's the final segment) of the just-updated index.m3u8 represent the last chunk. You should be able to modify that logic to your liking. If you can do this cleanly via a new API in Broadcaster we'd be happy to merge your work into the SDK!

I don't believe the HLS spec allows specifying a non-first segment for playback to begin with so you're probably limited to manually changing how the index.m3u8 is generated.

**Comment by gouravd** [comment]
Thanks, I will look into in in more detail
