### ISSUE TITLE
Why limitation of 4.3+

### ISSUE THREAD

**Issue by gouravd** [Kickflip/kickflip-android-sdk#31]
Why the android limitation of 4.3+. Media Codec is available since 4.1 and HLS support in Android is there since Honeycomb?

**Comment by OnlyInAmerica** [comment]
Good question! MediaCodec was available in API 16 but practically unusable until key improvements made in API 18. TLDR: Read MediaCodec author Andrew McFadden's [MediaCodec page](http://bigflake.com/mediacodec/) (Jump to Q9 for a quick answer).
- the [MediaCodec#createInputSurface()](http://developer.android.com/reference/android/media/MediaCodec.html#createInputSurface%28%29) API allows any necessary pixel format conversion needed between the Camera output and the MediaCodec input to be done by the GPU. Doing this conversion in software is a showstopper and must be implemented for a variety of different device capabilities. See this [StackOverflow issue](http://stackoverflow.com/questions/13703596/mediacodec-and-camera-colorspaces-dont-match).
- Android Compatibility Test Suite wasn't deployed until API 18, so there is no guarantee that the OEM's implementation of MediaCodec was correct or compatible with the output of the Camera.

Getting Kickflip to work reliably on Android 4.1 - 4.2 might take longer than it will for those platform versions to vaporize so I'm respectfully closing the issue :)
