### ISSUE TITLE
Error when get streams

### ISSUE THREAD

**Issue by nvhaiwork** [Kickflip/kickflip-android-sdk#34]
I'm used bellow code to get all streams, but got message: A Kickflip server error occurre.
I still can login user/ start srteam but I can't get streams. 
Please help me

```
    KickflipApiClient apiClient = Kickflip.getApiClient(this);
    apiClient.getStreamsByKeyword(null, 0, 100, new KickflipCallback() {
        @Override
        public void onSuccess(Response response) {

            mStreams = (List<Stream>) response;

            LogUtil.e("onSuccess", mStreams.size() + "adf");
            LogUtil.e("onSuccess", mStreams.toString());
        }

        @Override
        public void onError(KickflipException e) {
            LogUtil.e("onError", e.getMessage());
        }
    });
```

**Comment by OnlyInAmerica** [comment]
I believe pages start at 1, not 0. Could you change your page request and let me know if the issue persists?

Also, as always, make sure you're using the latest SDK version (`1.3.1` as of this writing).

Thanks for the report!

**Comment by nvhaiwork** [comment]
Ohhhhh, It works.
Thanks for your help.
