### ISSUE TITLE
Unknow Data Stream appearing

### ISSUE THREAD

**Issue by marudhupandiyang** [Kickflip/kickflip-android-sdk#38]
Im trying to implement a rtmp stream using kickflip.
I succeeded in doing so. But i see a extra data stream appearing on the stream. I know rtmp support has been stopped. But can someone tell me from where the Stream#0:1 Data none is coming from?? 

![screenshot from 2015-07-02 12-49-50](https://cloud.githubusercontent.com/assets/2351268/8471745/f5dab096-20b8-11e5-8855-3db391941059.png)

**Comment by gouravd** [comment]
DId you recompile FFMpeg and FFMpegwrapper on your own? 

Could you try using the already existing ones from this commit - https://github.com/Kickflip/kickflip-android-sdk/tree/962aa39367d147bae54ccd094e03888833d00a95
