### ISSUE TITLE
Unable to contact dev or cancel trial account

### ISSUE THREAD

**Issue by mjshiggins** [Kickflip/kickflip-android-sdk#46]
Developer won't respond to emails and they have no option on their portal to cancel a trial account. I'm assuming once the trial ends, we will be charged. Zero communication, zero support from us. This is the only method I found to contact and warn others.

**Comment by OnlyInAmerica** [comment]
@mjshiggins : Pardon the delay, our small team was out on vacation the last week. Your account subscription is now cancelled as you requested.
