### ISSUE TITLE
No options for canceling trial

### ISSUE THREAD

**Issue by ChrisDunaetz** [Kickflip/kickflip-android-sdk#50]
Hi, similar issue to: https://github.com/Kickflip/kickflip-android-sdk/issues/46

I'd like to cancel my free trial, but I can't get a hold of anyone to do so.

@mjshiggins maybe you can help?

**Comment by OnlyInAmerica** [comment]
Pardon our delayed response. Your Kickflip subscription has been cancelled and charges refunded.

**Comment by ChrisDunaetz** [comment]
great thanks

**Comment by OnlyInAmerica** [comment]
For future readers: You can always cancel your subscription from your account dashboard @ https://kickflip.io/dash/
