### ISSUE TITLE
Trial Cancel

### ISSUE THREAD

**Issue by ghost** [Kickflip/kickflip-android-sdk#51]
My username is 'justSomeAppLol'.

I need to cancel the trial, but there is no option within the console to do so.

The service is great, but I need to do more testing, and will not be launching app for some time.

**Comment by OnlyInAmerica** [comment]
Could you email support@kickflip.uservoice.com from the address you used to register with Kickflip?

**Comment by OnlyInAmerica** [comment]
For all future users, you may cancel your paid subscriptions at any time from your dashboard.
