### ISSUE TITLE
Cancel trial subscription

### ISSUE THREAD

**Issue by erikwolfe02** [Kickflip/kickflip-android-sdk#53]
I emailed a week after signing up (Oct 5) that I wanted my trial subscription cancelled. I was just charged though. I would like my money refunded and my account cancelled.

**Comment by OnlyInAmerica** [comment]
Pardon for the delay, but the charge is removed and your subscription cancelled. No further charges will be made to your account.

For other readers: You can always cancel subscriptions from your account dashboard @ https://kickflip.io/dash/

**Comment by erikwolfe02** [comment]
Thank you
