### ISSUE TITLE
Server Down

### ISSUE THREAD

**Issue by Anindya-Duti-Dhar** [Kickflip/kickflip-android-sdk#60]
Hello,
KickFlip server is down.
When do you think it is going to be up again ? It is really important to know !
Please take necessary steps as soon as possible.
Thanks.

**Comment by Miserlou** [comment]
DNS issue resolved.

On Tue, Oct 25, 2016 at 8:02 AM, Anindya Duti Dhar <notifications@github.com

**Comment by chrisballinger** [comment]
There was an issue with our DNS provider, it should be fixed now:
https://kickflip.io

On Tue, Oct 25, 2016 at 5:02 AM, Anindya Duti Dhar <notifications@github.com

**Comment by Anindya-Duti-Dhar** [comment]
Hello loving kickflip team,
Thanks for the customer support. The server is up now. 
Happy coding and happy to use kickflip.
Again thanks a lot 👍
