### ISSUE TITLE
Certificate Expired

### ISSUE THREAD

**Issue by SharedMocha** [Kickflip/kickflip-android-sdk#63]
Unable to add / Login users or many any api calls due to certificate expiration -

Issue below -
com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException:
Could not validate certificate: Certificate expired at Wed Apr 12 19:59:59 EDT 2017 (compared to Thu Apr 13 19:51:59 EDT 2017)

**Comment by OnlyInAmerica** [comment]
Thanks for the report. The SSL cert has been re-issued.
